# Screenshots — copia para o clipboard
bindsym {
    Print             exec grimshot copy output
    Alt+Print         exec grimshot copy active
    Ctrl+Print        exec grimshot copy area
    # versões que salvam em arquivo, com Shift
    Shift+Print       exec grimshot save output
    Alt+Shift+Print   exec grimshot save active
    Ctrl+Shift+Print  exec grimshot save area
}
